### ISSUE TITLE
If i can help

### ISSUE THREAD

**Issue by UnEnanoMas** [Kingbobs/PrisonCells#1]
[CellPE 2.0.3](https://drive.google.com/file/d/1EWI4viSOJBuXX3iR_Ibxa4NoLqYnrQo7/view?usp=sharing)

Try unzipping it, and look at the code to see if it helps you in anything

[Unphar](https://phar.scer.io)

(PD: It's not mine)

**Comment by Kingbobs** [comment]
I still Dont know whats Makeing the error
